[16.0][ADD] edi_sale_utm_oca
chaule97/edi-framework pull request #1
Opened 2024-07-19 05:13 UTC by chaule97

-  this module `edi_sale_utm_oca` provide utm sources to set on an exchange type.

2024-07-24 03:50 UTC, QuocDuong1306 requested changes
Also maybe missing `CONFIGURE.rst`

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/__manifest__.py
> +}
Please remove `"auto_install": True`

Add `"maintainers": ["simahawk"],`

Change to `Allows to define an utm source on an exchange type and automatically set it on the sale order when it is created.`

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/__manifest__.py
> +    "name": "EDI Sale utm",
```suggestion
    "name": "EDI Sale UTM",
```

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/edi_exchange_type.py
> +    )
Maybe need a `help`

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +    def _set_source_id(self, vals):
```suggestion
    def _edi_set_source_id(self, vals):
```

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +                vals["source_id"] = exchange_type.edi_source_id.id
Just set if `source_id` not in `vals`

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +
```suggestion
```

2024-07-24 03:50 UTC, QuocDuong1306 commented on edi_sale_utm_oca/tests/test_sale_order.py
> +        )
reuse the test in `edi_sale_oca` instead

You can have a look at `edi_sale_ubl_oca` (v14, `edi/pull/759`) to get the idea to test

2024-07-24 03:58 UTC, QuocDuong1306 reviewed
Sorry, I think the good approach is creating 2 modules instead: `edi_utm_oca` and `edi_sale_utm_oca`

You can reference `edi_state_oca` and `edi_sale_ubl_oca` to have an idea

discuss with me, If you have difficulty when researching

2024-07-25 10:00 UTC, QuocDuong1306 requested changes

2024-07-25 10:00 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +        return super().create(vals_list)
Why you don't use `_edi_set_source` on `edi_utm_oca` 

And please put this one in `def _edi_set_source` of `edi_utm_oca`

```
if vals.get("origin_exchange_record_id"):
            exchange_record = self.env["edi.exchange.record"].browse(
                vals["origin_exchange_record_id"]
            )

            exchange_type = exchange_record.type_id

            conditions = [
                exchange_type,
                exchange_type.edi_source_id,
                "edi_source_id" not in vals,
            ]

            if all(conditions):
                vals["edi_source_id"] = exchange_type.edi_source_id.id

2024-07-25 10:00 UTC, QuocDuong1306 commented on edi_sale_utm_oca/readme/DESCRIPTION.rst
> +This module allows to set a utm source on an exchange type and sets it automatically when the order is created.
```suggestion
This module allows to set a utm source on an exchange type and sets it automatically when the sale order is created.
```

2024-07-25 10:00 UTC, QuocDuong1306 commented on edi_sale_utm_oca/tests/test_sale_order.py
> +        )
You can test the same with [this test](https://github.com/OCA/edi-framework/blob/16.0/edi_sale_oca/tests/test_order.py)

2024-07-26 03:20 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +        return super().create(vals_list)
sorry, please ignore the block, just need to re-use `_edi_update_source`

2024-07-27 10:31 UTC, QuocDuong1306 requested changes
Could you create a view to put `edi_source_id` into [this group](https://github.com/OCA/edi-framework/blob/d2dd6121f838d3a788b3a318776b7e50dccc37f3/edi_sale_oca/views/sale_order.xml#L12)

2024-07-27 10:31 UTC, QuocDuong1306 commented on edi_sale_utm_oca/__manifest__.py
> +    "depends": ["sale_management", "edi_utm_oca"],
```suggestion
    "depends": ["edi_sale_oca", "edi_utm_oca"],
```
We need the `origin_exchange_record_id` on Sale Order

2024-07-27 10:31 UTC, QuocDuong1306 commented on edi_sale_utm_oca/tests/test_sale_order.py
> +        )
```suggestion
        self.assertEqual(
            order.edi_source_id,
            self.env.ref("edi_utm_oca.utm_source_edi"),
        )
```

2024-07-29 02:58 UTC, QuocDuong1306 approved these changes
LG,

Thank a Chau

2024-08-29 08:10 UTC, QuocDuong1306 approved these changes
Pre-approving

2024-08-29 08:10 UTC, QuocDuong1306 commented on edi_sale_utm_oca/models/sale_order.py
> +    ]
```suggestion
    _inherit = "sale.order"
```

2024-08-29 08:10 UTC, QuocDuong1306 commented on edi_sale_utm_oca/readme/DESCRIPTION.rst
> +This module allows to set a utm source on an exchange type and sets it automatically when the sale order is created.
```suggestion
This module allows to set a utm source on an exchange type and sets it automatically when the sale order is created through this exchange type.
```

2024-08-29 09:37 UTC, QuocDuong1306 approved these changes

2024-09-04 04:38 UTC, chaule97 commented
Hi @QuocDuong1306 , can you review my PR again

2024-09-04 08:47 UTC, QuocDuong1306 approved these changes
Pre-approving

2024-09-04 08:47 UTC, QuocDuong1306 commented on edi_utm_oca/readme/DESCRIPTION.rst
> +This module automatically sets the EDI source on models that have a source_id field when they are created.
```suggestion
This module automatically assigns the EDI source to records created through the EDI mechanism.
```

2024-09-12 09:00 UTC, merged